### ISSUE TITLE
after navigating to google pay it shows payment is risky

### ISSUE THREAD

**Issue by Amolnigdikar** [googletez/inapp-payment-samples#8]

**Comment by dibyanshuanand** [comment]
+1, I too am facing the same issue

**Comment by Bhagat8533** [comment]
I am also facing this issue. Anyone has any solution?

**Comment by patugosavi** [comment]
I am also facing this issue.

**Comment by cyber-vendetta** [comment]
I am also facing this issue, Hopefully this error is due to the lack of adherence to NPCI prerequisites from Merchant App. In the new update, it is mandatory for the Merchant App to have a verified Business Account UPI (using Gpay for Business) to receive payments. This procedure takes approx. 2 days to verify your payments profile( PAN Card, GSTIN, or other modes of documents will be verified). Fulfilling the above issue must solve the error. This is not a design flaw as this UPI intent call is being used by many apps like Jio, Amazon etc. I am currently working on the verification aspect. Will update this thread if i am successful.

**Comment by VirtualCreativities** [comment]
i am also facing the same since last week of june, only Paytm is accepting while other UPI Apps are not processing payments. 
Already verified GPay Business Account with GST & PAN and got the working Merchant code , activated a year ago.

**Comment by AjayDeveloper** [comment]
I am also facing the same issue. but as per @cyber-vendetta Merchant App to have a verified Business Account UPI ,
I do it right now and app showing its verified immdiatley tried to do this but not working shall I wait at least 2 days  ??

**Comment by RandomCatGit** [comment]
This is caused by recent changes to security in UPI transactions to prevent fraud. See https://stackoverflow.com/a/68800878/4697928

**Comment by Amolnigdikar** [comment]
Business verification is needed for your business account as per google customer support

**Comment by RandomCatGit** [comment]
What about normal accounts? They too are getting rejected. If you scan via app and pay, basic 4 params are enough. If you generate the URI and open the app to pay, issue occurs. Any idea why that is? @Amolnigdikar

**Comment by Amolnigdikar** [comment]
@RandomCatGit Sorry don't have any idea about personal accounts

**Comment by RandomCatGit** [comment]
> @RandomCatGit Sorry don't have any idea about personal accounts

Ahhh ok. I am currently trying to make a work around but it involves removing payment confirmation from your app and the biller has to verify manually... Will update soon.

**Comment by zimmy9537** [comment]
@RandomCatGit @Amolnigdikar @patugosavi did you guys solved this issue? I am facing this issue when passing those 4 parameters through intent

**Comment by RandomCatGit** [comment]
I have a workaround for this as of now but it takes some manual work to achieve the result. https://stackoverflow.com/a/68800878/4697928

**Comment by zimmy9537** [comment]
@RandomCatGit this might help, did you look after this any before?
https://web.archive.org/web/20200921110005/https://www.npci.org.in/sites/default/files/UPI%20Linking%20Specs_ver%201.6.pdf

**Comment by zimmy9537** [comment]
still i have no idea how to proceed

**Comment by RandomCatGit** [comment]
> still i have no idea how to proceed

I have mentioned the solution in that stackoverflow questions

**Comment by Joshjoyb** [comment]
Is integrating a payment gateway the only way?

**Comment by saikrishnasaski** [comment]
I am also facing similar issue, I am using VPA id which I got from Gpay for business but no luck.
